2025-09-09 22:24:29,945 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:24:43,190 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:24:56,158 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:24:56,159 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:04,274 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:04,275 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:17,102 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:17,103 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:24,105 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:24,111 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:29,639 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:29,641 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:35,875 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:35,877 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:40,553 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:25:40,555 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:25:40,663 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:40,664 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:46,145 - __main__ - ERROR - Bot xatosi (1/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:57,230 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:25:57,232 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:25:59,340 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:25:59,343 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:26:07,343 - __main__ - ERROR - Bot xatosi (2/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:26:19,576 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:26:19,579 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:26:30,487 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:26:30,488 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:26:36,402 - __main__ - ERROR - Bot xatosi (3/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:01,942 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:01,945 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:27:07,513 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:07,515 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:27:09,596 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:27:09,597 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:27:13,127 - __main__ - ERROR - Bot xatosi (4/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:41,822 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:41,823 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:27:54,215 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:27:54,217 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:27:56,321 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:27:56,321 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:27:59,831 - __main__ - ERROR - Bot xatosi (5/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:28:08,453 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:28:08,455 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:28:48,306 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:28:48,308 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:29:54,812 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:29:54,813 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:30:14,310 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:30:14,311 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:31:01,306 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:31:01,308 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:31:21,042 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:31:21,044 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:32:27,772 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:32:27,774 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:33:09,039 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:33:09,040 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:33:34,268 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:33:34,269 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:34:15,539 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:34:15,541 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:34:30,673 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:34:30,674 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:42:18,339 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:42:18,340 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:42:21,467 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:42:21,468 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:42:23,837 - __main__ - ERROR - Bot xatosi (1/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:42:34,947 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:42:34,949 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:42:37,048 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:42:37,049 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:42:40,562 - __main__ - ERROR - Bot xatosi (2/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:42:51,504 - __main__ - INFO - Start buyrug'i: Fazliddin
2025-09-09 22:43:01,694 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:01,695 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:43:03,850 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:43:03,850 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:43:07,070 - __main__ - ERROR - Bot xatosi (3/5): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:39,285 - __main__ - INFO - Bot ishga tushdi: @ttjqdu_bot
2025-09-09 22:43:39,285 - __main__ - INFO - Bot polling boshlandi
2025-09-09 22:43:42,117 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:42,118 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:43:46,632 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:46,633 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:43:53,268 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:53,269 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:43:58,633 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:43:58,635 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:01,000 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:01,002 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:06,850 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:06,852 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:09,541 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:09,542 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:14,913 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:14,915 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:18,034 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:18,036 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:23,685 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:23,686 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:27,800 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:27,801 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:30,932 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:30,940 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:37,048 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:37,049 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:41,162 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:41,163 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:51,295 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:51,296 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:44:57,845 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:44:57,847 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:45:15,997 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:45:15,998 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:45:26,135 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:45:26,138 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:46:00,289 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:46:00,290 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:46:05,665 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:46:05,667 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:47:09,076 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:47:09,077 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:48:11,195 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:48:11,196 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:48:16,576 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:48:16,577 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:49:20,128 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:49:20,129 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:50:22,245 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:50:22,246 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:50:27,618 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:50:27,619 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:51:30,968 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:51:30,969 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:52:33,090 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:52:33,092 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:52:38,465 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:52:38,467 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:53:41,821 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:53:41,823 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:54:44,405 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:54:44,407 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:54:49,771 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:54:49,773 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:55:53,767 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:55:53,769 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:56:55,885 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:56:55,887 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:57:01,252 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:57:01,254 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:57:48,079 - __main__ - INFO - Start buyrug'i: Fazliddin
2025-09-09 22:58:05,479 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:05,481 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:10,854 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:10,855 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:15,325 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:15,326 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:20,693 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:20,695 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:23,069 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:23,070 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:28,440 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:28,442 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:31,062 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:31,063 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:36,675 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:36,677 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-09-09 22:58:39,803 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-09-09 22:58:39,804 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "D:\github\new_bot\.venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

